#!/usr/bin/env python

"""
Change the locations of mayapy and the export_alembic_custom.py accordingly
to your install directories
"""

import subprocess

cmd = [
    '/Applications/Autodesk/maya2016/Maya.app/Contents/bin/mayapy',
    '/Users/bjoern_siegert/GitHub/tbt_maya/python/export_alembic_custom.py',
]

subprocess.call(cmd)